### ISSUE TITLE
FCS Project

### ISSUE THREAD

**Issue by tanjapetersen** [tanjapetersen/geomag#3]
GNS wants to re-structure the I:/drive. File Classification System. Maria Molina is my contact person.

There will be two different Level 1 folders for geomag:

1. Collections and Database Mgmt - for documents, spreadsheats, pdfs. They will go into an ACM structure in the future.

2. Datasets – actual data or links (“shortcuts”) to actual data. This will point to the geomag data on the Linux system in /amp/magobs/.

**Tasks**
- [ ] create file structure & decide on naming

- [ ] write description for subfolders

- [ ] decide on read-write access information -- Cameron Scragg

- [ ] add readme files within the directories

- [ ] house cleaning & moving files -- On I:/drive & /amp/magobs/. Create wiki page that documents this!
