### ISSUE TITLE
IAGA 2018 -- geomag observatory workshop

### ISSUE THREAD

**Issue by tanjapetersen** [tanjapetersen/geomag#4]
- [x]  IAGA financial support

- [x] check budget

- [x] submit abstract: SBA poster, Antarctic fieldwork

- [x] apply for travel approval

- [x] registration & travel arrangements

- [x] New DIM for the "Field" theodolite -- estimated costs in Lars's email 1/11/2016

**Tasks & Goals**

- [ ] ideas for SBA huts renovation - fit for purpose

- [ ] RaspberryPi for API (Potsdam person)

- [x] feedback & input on my SBA poster for geomag review

**Comment by tanjapetersen** [comment]
Trip report on I;\Conferences\Conference reports. Also emailed it to Gill Jolly. Notes, presented poster etc are in the geomag Workshop & Conferences folder under IAGA 2018
